dotnet/maui-samples

HelloAndroid/HelloAndroid.csproj
HelloForms.Android/HelloForms.Android.csproj
README.md
global.json

* `$(OutputType)` = `Exe` is what flags an app vs library
https://github.com/xamarin/xamarin-android/pull/4604
* New `Run` target
https://github.com/xamarin/xamarin-android/pull/4609

Bump to Microsoft.Android.Sdk 10.4.99.51

---

HelloForms.Android/Properties/AndroidManifest.xml

This will fix a build warning.

[HelloForms.Android] targetSdkVersion should be 29

---

azure-pipelines.yml

`dotnet --list-sdks` is more appropriate

[build] improve log output during .NET install

---

azure-pipelines.yml
global.json

Fixes https://github.com/xamarin/net6-samples/issues/18.

Bump the iOS Sdk to work with preview 7. Fixes #18.

---

HelloForms/HelloForms.csproj

We forgot to update the shared Xamarin.Forms project from `netcoreapp5.0` to `net5.0`.

HelloForms.csproj should be net5.0

---

global.json

Tested with 5.0.100-preview.7.20317.11.

[iOS] Switch to follow the main branch.

---

global.json

* Adds API 30 bindings (Android 11.0)
* Support for multiple `$(RuntimeIdentifiers)`
* Fixes for linking

Update to Microsoft.Android.Sdk 11.x

---

global.json

Fixes https://github.com/xamarin/net6-samples/issues/35.

Bump iOS to get fix for #35.

---

HelloiOS/AppDelegate.cs

The HelloiOS project was plain green screen, so I thought it would be
good to have a single `UILabel` with the same text as the HelloAndroid
project.

[iOS] make HelloiOS the same as HelloAndroid

---

README.md
azure-pipelines.yml
global.json

* Microsoft.NET.Workload.Android 11.0.200.85

Bump to .NET 6.0.100-preview.1.21103.13

---

HelloAndroid/HelloAndroid.csproj
HelloAndroid/MainActivity.cs
HelloAndroid/Resources/values/strings.xml
HelloForms/HelloForms.csproj

Addresses issue
https://github.com/dotnet/net6-mobile-samples/issues/62

disable fast deployment for android

---

HelloMaui/HelloMaui.csproj
README.md
azure-pipelines.yml
global.json
vs/net6-samples-maui.sln

* Android 11.0.200.148
* iOS 14.4.100.1180
* MacCatalyst 14.3.100.325

Bump to .NET 6.0.100-preview.2.21155.3

---

HelloMaui/MainPage.xaml
HelloMaui/MainPage.xaml.cs

Added more controls (slider, switch) and a counter click action. Styled with .NET colors.

HelloMaui counter

---

README.md
azure-pipelines.yml

This includes a signed MacCatalyst package now.

Bump to latest iOS & MacCatalyst packages

---

.vscode/extensions.json

C# extension has `ms-dotnettools.csharp` id.

Correct extensions.json

---

README.md
azure-pipelines.yml
global.json

* Android 11.0.200.196
* iOS 14.4.100.1326
* macOS 11.1.100.1379
* MacCatalyst 14.3.100.471

Bump to .NET 6.0.100-preview.3.21202.5

---

HelloMauiWinUI3/HelloMauiWinUI3.sln
azure-pipelines.yml

When your SLN  configuration is set to Any CPU just default everything to x64/deploy

Fix AnyCPU to default to x64

---

HelloMaui/Android/MainActivity.cs
HelloMaui/Android/Resources/values/colors.xml
HelloMaui/HelloMaui.csproj

Also added a @(MauiSplashScreen) using the app icon and a solid color.
Updated a color to match the default Maui template:
https://github.com/dotnet/maui/blob/07438b70edfdd4fc804b0991ef61cf98d62a39f0/src/Templates/src/maui-mobile/Android/Resources/values/colors.xml#L4

Bump to Microsoft.Maui 6.0.100-preview.4.618

---

README.md
azure-pipelines.yml
global.json

Bump to .NET 6.0.100-preview.5.21302.13

---

HelloMaui/HelloMaui.csproj
HelloMaui/Startup.cs
HelloMauiWinUI3/HelloMauiWinUI3/HelloMauiWinUI3.csproj

There is a minor API break, a new `using` statement is required.
I also made some minor fixes in `.csproj` files.

Bump to .NET MAUI 6.0.100-preview.5.763

---

HelloMaui/Platforms/iOS/Entitlements.plist
README.md
azure-pipelines.yml

Fixes: https://github.com/dotnet/maui-samples/issues/180

[build] fix .NET 6 version

---

6.0/Animations/README.md
6.0/Apps/Calculator/README.md
6.0/Apps/WeatherTwentyOne/README.md
6.0/Navigation/FlyoutPageSample/README.md
6.0/Navigation/ShellFlyoutSample/README.md
6.0/Navigation/ShellMixedSample/README.md
6.0/Navigation/ShellTabBarSample/README.md
6.0/Navigation/TabbedPage/README.md

Fixed YAML to use correct `dotnet-maui` product and language formatting

Fix frontmatter formatting, taxonomy

---

6.0/PlatformIntegration/InvokePlatformCodeDemos/InvokePlatformCodeDemos/MainPage.xaml.cs

This is a fix for [Issue 225](https://github.com/dotnet/maui-samples/issues/225)

fix copy-paste bug

---

6.0/UserInterface/Layouts/FlexLayoutDemos/FlexLayoutDemos/Views/PhotoWrappingPage.xaml.cs

Force an image height/width

---

README.md

Update README.md and add CommunitySamples

---

6.0/Animations/Animations/Animations.csproj

Fix https://github.com/dotnet/maui-samples/issues/205

Update to the stable CommunityToolkit version

---

6.0/Animations/Animations/Pages/ScalePage.xaml

Text for this Semantic Properties appears to come from a copy paste and does not reflect the action this page does.

Edits Semantic Properties  For Scale

---

7.0/Fundamentals/ContextMenu/ContextMenuSample/MainPage.xaml

Rely on the styles, don't hardcode the color here.

Fix for dark theme so text color will be visible.

---

7.0/UITesting/BasicAppiumNunitSample/README.md

2 minor errors in the UITesting Appium/NUnit readme

Update Appium/NUnit README

---

7.0/UITesting/BasicAppiumNunitSample/README.md

Appium readme updates

---

8.0/UserInterface/Views/IndicatorViewDemos/IndicatorViewDemos/Views/BasicIndicatorViewPage.xaml
8.0/UserInterface/Views/IndicatorViewDemos/IndicatorViewDemos/Views/ConfigurableIndicatorViewPage.xaml
8.0/UserInterface/Views/IndicatorViewDemos/IndicatorViewDemos/Views/TemplatedIndicatorViewPage.xaml

Fix CarouselView sizing

---

8.0/Apps/GameOfLife/README.md

Fix readme typo

---

.github/workflows/quest-bulk.yml
.github/workflows/quest.yml
quest-config.json

Install quest

---

quest-config.json

Add MAUI parent work item ID

---

.github/workflows/quest-bulk.yml
.github/workflows/quest.yml

Use OIDC keys for the OSPO API

---

Upgrading/CustomRenderer/MultiProject/Entry/README.md

This sample is appearing in the samples browser under Xamarin, which we don't want to happen.

Remove metadata

---

8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.Droid/NativeEmbeddingDemo.Droid.csproj
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.MacCatalyst/AppDelegate.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.MacCatalyst/MainViewController.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.MacCatalyst/NewTaskSceneDelegate.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.MacCatalyst/SceneDelegate.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.iOS/AppDelegate.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.iOS/Info.plist
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.iOS/MainViewController.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.iOS/NativeEmbeddingDemo.iOS.csproj
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.iOS/NewTaskSceneDelegate.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.iOS/NewTaskViewController.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo.iOS/SceneDelegate.cs
8.0/PlatformIntegration/NativeEmbeddingDemo/NativeEmbeddingDemo/NativeEmbeddingDemo.csproj

Sample updates

---

8.0/Apps/PointOfSale/src/PointOfSale/Converters/CheckedColorConverter.cs
8.0/Apps/PointOfSale/src/PointOfSale/Resources/Styles/Converters.xaml

Fixed wrong namespace in PointOfSale project

Fixed namespace

---

quest-config.json

dotnet/docs-tools#413 enhances Sequester to allow for different parents per semester. This PR updates the config to match.

enhance config for semester rollover

---

8.0/UserInterface/Views/ListViewDemos/ListViewDemos/App.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/ContextMenuItemsPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/DataTemplateSelectorPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/GroupingPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/PullToRefreshPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/RightToLeftListPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/RuntimeItemSizingPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/ScrollByItemPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/ScrollByItemWithGroupingPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/SelectionPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/TemplatedHeaderFooterPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/TextHeaderFooterPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/TextListPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/VerticalListPage.xaml
8.0/UserInterface/Views/ListViewDemos/ListViewDemos/Views/ViewHeaderFooterPage.xaml

Replace SL with Grid

---

.github/workflows/build-all.yml
.github/workflows/build-pr.yml

Move to macOS 15 so we can use Xcode 16.

Bump macOS runner

---

9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo.sln
9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/MainPage.xaml.cs
9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/MauiProgram.cs
9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/Resources/Raw/wwwroot/index.html
9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/Resources/Raw/wwwroot/scripts/HybridWebView.js

Update the HybridWebView sample to work with .NET 9 GA, and to call .NET methods from JavaScript.

Call .NET methods from JS

---

.github/workflows/quest-bulk.yml
.github/workflows/quest.yml

The QUEST workflows are out of date and no longer work (throw an error).

Update QUEST workflows

---

9.0/Fundamentals/BehaviorsDemos/BehaviorsDemos/HomePageViewModel.cs
9.0/Fundamentals/BehaviorsDemos/BehaviorsDemos/Person.cs
9.0/Fundamentals/BehaviorsDemos/BehaviorsDemos/Views/Code/EventToCommandBehaviorPageCode.cs
9.0/Fundamentals/DataBindingDemos/DataBindingDemos/Views/AlternativeCodeBindingPage.xaml.cs
9.0/Fundamentals/DataBindingDemos/DataBindingDemos/Views/AlternativeXamlBindingPage.xaml
9.0/Fundamentals/DataBindingDemos/DataBindingDemos/Views/BasicCodeBindingPage.xaml.cs
9.0/Fundamentals/DataBindingDemos/DataBindingDemos/Views/MultiBindingConverterCodePage.cs
9.0/Fundamentals/DataBindingDemos/DataBindingDemos/Views/MultiBindingStringFormatCodePage.cs
9.0/UserInterface/Layouts/GridDemos/GridDemos/Views/Code/ColorSlidersGridPage.cs
9.0/UserInterface/Views/ScrollViewDemos/ScrollViewDemos/NamedColor.cs
9.0/UserInterface/Views/ScrollViewDemos/ScrollViewDemos/Views/Code/ColorListPage.cs

Compile code bindings

---

9.0/Apps/DeveloperBalance/DeveloperBalance/Pages/MainPage.xaml
9.0/Apps/DeveloperBalance/DeveloperBalance/Pages/ManageMetaPage.xaml
9.0/Apps/DeveloperBalance/DeveloperBalance/Pages/TaskDetailPage.xaml

Incorporates the changes from https://github.com/dotnet/maui/pull/26903 and https://github.com/dotnet/maui/pull/26920 also in the sample app

Improve accessibility Developer Balance sample app

---

9.0/Apps/DeveloperBalance/Pages/ManageMetaPage.xaml

Bring over these changes Javier made here: https://github.com/dotnet/maui/pull/27139

Bring over Javier's changes

---

9.0/Apps/DeveloperBalance/Pages/ManageMetaPage.xaml
9.0/Apps/DeveloperBalance/Pages/ProjectDetailPage.xaml

Partially Resolves: 
* https://github.com/dotnet/maui/issues/26185
* https://github.com/dotnet/maui/issues/26128

More DeveloperBalance A11y Fixes

---

9.0/Apps/DeveloperBalance/Pages/ProjectListPage.xaml

Make the Project Section accessible using the keyboard in the DeveloperBalance App sample.
Related with https://github.com/dotnet/maui/pull/27222

Fix keyboard navigation issue on DeveloperBalance App

---

9.0/Apps/DeveloperBalance/App.xaml.cs
9.0/Apps/DeveloperBalance/PageModels/ManageMetaPageModel.cs
9.0/Apps/DeveloperBalance/PageModels/ProjectDetailPageModel.cs
9.0/Apps/DeveloperBalance/Pages/Controls/TaskView.xaml
9.0/Apps/DeveloperBalance/Pages/MainPage.xaml
9.0/Apps/DeveloperBalance/Pages/ManageMetaPage.xaml
9.0/Apps/DeveloperBalance/Pages/ProjectDetailPage.xaml
9.0/Apps/DeveloperBalance/Pages/TaskDetailPage.xaml
9.0/Apps/DeveloperBalance/Platforms/iOS/SemanticScreenReaderAsyncImplementation.cs
9.0/Apps/DeveloperBalance/Services/AnnouncementHelper.cs
9.0/Apps/DeveloperBalance/Services/IAsyncAnnouncement.cs

This PR brings up a bunch of changes to help with accessibility. One large change is bringing over the AnnouncementHelper class and associated changes from the [Recipe's](https://github.com/rachelkang/recipeSearch/tree/8b65438d95ef7152467ff695d65475f4131586e0) app
This PR would allow us to A11y-Resolve the following issues:
* https://github.com/dotnet/maui/issues/27463
* https://github.com/dotnet/maui/issues/27462
* https://github.com/dotnet/maui/issues/27461
* https://github.com/dotnet/maui/issues/27460
* https://github.com/dotnet/maui/issues/27432
* https://github.com/dotnet/maui/issues/27431
* https://github.com/dotnet/maui/issues/27429
* https://github.com/dotnet/maui/issues/27428
* https://github.com/dotnet/maui/issues/27424
* https://github.com/dotnet/maui/issues/27423
* …

[DeveloperBalance] Many iOS Accessibility Changes

---

9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/MauiProgram.cs
9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/Resources/Raw/wwwroot/scripts/HybridWebView.js

In .NET (MAUI) 9 SR4, it's possible to bubble up exceptions from JS to .NET.

Bubble up exceptions from JS to .NET

---

9.0/Packaging/NuGetWithMSBuildFiles/README.md

Remove msbuild from readme metadata.

Remove msbuild from metadata
