dotnet/maui-samples

- azure-pipelines.yml
- global.json
Now that this repo is in a working state, I think it's worth adding something simple here to make sure these samples continue to build.
Using: https://docs.microsoft.com/en-us/dotnet/core/tools/using-ci-with-cli
I've been able to install any build of .NET 5 found here:
https://github.com/dotnet/installer#installers-and-binaries
This builds iOS and Android on macOS and just Android on Windows.
> Set up CI with Azure Pipelines

- HelloForms.Android/HelloForms.Android.csproj
To make it build with ILLink enabled. We should not need these once
we have AndroidX targeting net5
> Add few more package references

- Directory.Android.targets
- HelloAndroid/HelloAndroid.csproj
- HelloForms.Android/HelloForms.Android.csproj
- HelloForms.iOS/HelloForms.iOS.csproj
- HelloiOS/HelloiOS.csproj
- README.md
- azure-pipelines.yml
- global.json
Fixes: https://github.com/xamarin/net5-samples/issues/16
`$(TargetFramework)` should be `net5.0` now.
Android has the following fixes:
* https://github.com/xamarin/xamarin-android/pull/4663
* https://github.com/xamarin/xamarin-android/pull/4692
This enables several workarounds to be removed.
Also use the same .NET 5 build as `xamarin-android`:
https://github.com/xamarin/xamarin-android/blob/cde7b79dce48d9f3fdfc396641a01fb27d165042/build-tools/automation/azure-pipelines.yaml#L53
I updated the `README.md` and our Azure DevOps build pipeline.
> Bump Xamarin SDKs

- Directory.Android.targets
- Directory.Build.targets
- HelloForms.Android/HelloForms.Android.csproj
- README.md
Context: https://github.com/xamarin/AndroidX/pull/103
We removed the .NET framework 4.5 MSBuild task from VectorDrawable.
The Android projects in this repo no longer need any temporary workarounds.
> [android] update Xamarin.AndroidX.VectorDrawable

- azure-pipelines.yml
The default branch has been updated to `main`, and the pipeline build
triggers should be updated to reflect that change.
> [ci] Update primary and PR triggers

- HelloForms.Android/HelloForms.Android.csproj
- HelloForms.iOS/HelloForms.iOS.csproj
- HelloForms/HelloForms.csproj
- azure-pipelines.yml
When I originally tested this, I was getting a crash in Xamarin.Forms
on startup:
FATAL EXCEPTION: main
Process: com.microsoft.net5.helloforms, PID: 12221
android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'AndroidPlatformServices' threw an exception.
---> System.NotImplementedException: The method or operation is not implemented.
at Internal.Cryptography.HashProviderDispenser.NotImplementedHashProvider.get_HashSizeInBytes()
at System.Security.Cryptography.IncrementalHash..ctor(HashAlgorithmName name, HashProvider hash)
at System.Security.Cryptography.IncrementalHash.CreateHash(HashAlgorithmName hashAlgorithm)
at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
at Xamarin.Forms.Forms.AndroidPlatformServices..cctor()
--- End of …
> Bump to .NET 5.0.100-rc.1.20365.11

- HelloAndroid/Properties/AndroidManifest.xml
- HelloForms.Android/Properties/AndroidManifest.xml
- README.md
These projects currently hit the warning:
warning XA1006: The TargetFrameworkVersion (Android API level 30) is higher than the targetSdkVersion (29). Please increase the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match.
We need to target API 30 instead.
> [android] use targetSdkVersion="30"

- NuGet.config
Without the feed it's not possible to build the `main` branch.
```sh
/Users/bruno/git/net6-samples/HelloForms.Droid/HelloForms.Droid.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.android-x86 with version (= 6.0.0-alpha.1.20453.28) [/Users/bruno/git/net6-samples/net6-samples.sln]
/Users/bruno/git/net6-samples/HelloForms.Droid/HelloForms.Droid.csproj : error NU1102:   - Found 436 version(s) in dotnet5 [ Nearest version: 6.0.0-alpha.1.20420.3 ] [/Users/bruno/git/net6-samples/net6-samples.sln]
/Users/bruno/git/net6-samples/HelloForms.Droid/HelloForms.Droid.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 5.0.0-preview.8.20407.11 ] [/Users/bruno/git/net6-samples/net6-samples.sln] …
```
> Add net6 package feed

- Directory.Build.targets
- HelloAndroid/HelloAndroid.csproj
- HelloAndroid/Resources/values/strings.xml
- HelloForms.Droid/HelloForms.Droid.csproj
- HelloForms.iOS/HelloForms.iOS.csproj
- HelloForms/HelloForms.csproj
- HelloiOS/HelloiOS.csproj
- README.md
- azure-pipelines.yml
- global.json
* Bump to .NET 5.0.100-rc.2.20459.1
* Bump to Microsoft.Android.Sdk 11.0.100-ci.master.127
* Consolidate `@(PackageReference)` needed for Xamarin.Forms projects
in `Directory.Build.targets`.
* No need to declare `$(RuntimeIdentifier)` in Android projects. Use
the defaults for these samples.
* `Hello, .NET 6!`
* `ProduceReferenceAssembly=true` is default in .NET 5+, not needed in
`HelloForms.csproj`.
* Update `README.md` for Android specifics.
> [android] use TargetFramework=net5.0-android and other cleanup

- README.md
- azure-pipelines.yml
- global.json
- scripts/provision.csx
Context: https://github.com/xamarin/net6-samples/issues/35#issuecomment-704495534
Context: https://github.com/dotnet/sdk/commit/37d5ade0f863258a78313b8421eae0eb02d25c69
To account for the rename of `@(SdkSupportedTargetPlatform)` to
`@(SdkSupportedTargetPlatformVersion)`, we need to:
* Use .NET 5.0.100-rc.2.20480.7
* Use Microsoft.Android.Sdk 11.0.100-ci.master.169
* Use Microsoft.iOS.Sdk 14.0.100-ci.main.559
> Bump to .NET 5.0.100-rc.2.20480.7

- HelloAndroid/HelloAndroid.csproj
- HelloForms/Directory.Build.props
- README.md
- azure-pipelines.yml
Context: https://github.com/xamarin/xamarin-android/pull/5236
Fixes problem with Fast Deployment on Android caused by incorrect
paths in `@(ResolvedFilesToPublish)` from the dotnet/sdk.
Hoping it might help the random iOS failure, too? We saw things in the
build log such as:
asset directory did not exist: /Users/runner/work/1/s/HelloAndroid/obj/Debug/net5.0-android/assets/ (TaskId:253)
Executing link --manifest /Users/runner/work/1/s/HelloAndroid/obj/Debug/net5.0-android/android/manifest/AndroidManifest.xml [...]
ILLINK : error MT2301: The linker step 'Setup' failed during processing. [/Users/runner/work/1/s/HelloiOS/HelloiOS.csproj]
`net6-samples.sln` will build projects in parallel, so we're not sure
if the Android log message is affecting the iOS build or not.
> Bump to Microsoft.NET.Workload.Android 11.0.100.209

- global.json
Since .NET 5.0 GA came out yesterday, the GA version is preferred over
the rtm build currently specified in `global.json`.
Set `"rollForward": "disable"`, so the right version is used by
default.
> Pin to .NET 5.0.100-rtm.20509.5

- HelloForms/Directory.Build.props
Testing the HelloForms app I noticed `CoreCompile` always runs:
Building target "CoreCompile" completely.
Input file "Shared/**.cs" does not exist.
We actually need to be using `Shared\**\*.cs` as the wildcard. I needed
to fix the Android and iOS directories as well.
> [HelloForms] fix *.cs wildcards

- HelloAndroid/HelloAndroid.csproj
- HelloAndroid/Properties/AndroidManifest.xml
- HelloForms/Android/AndroidManifest.xml
- HelloForms/Directory.Build.props
- HelloForms/HelloForms.csproj
- HelloForms/iOS/Info.plist
- HelloiOS/HelloiOS.csproj
- HelloiOS/Info.plist
- README.md
- azure-pipelines.yml
- global.json
- scripts/provision.csx
* Everything is `net6.0` now
* Android 11.0.100.239
* iOS 14.2.100.27
* `$(_DotNetPackageVersion)` can use 5.0.0 stable NuGet packages
> Bump to .NET 6.0.100-alpha.1.20562.2

- HelloForms/Directory.Build.props
- NuGet.config
- README.md
- azure-pipelines.yml
- global.json
- scripts/provision.csx
* Bump to Xcode 12.3
* Bump to Microsoft.NET.Workload.Android 11.0.200.72
* Bump to Microsoft.NET.Workload.iOS 14.3.100-ci.main.1045
* Remove .NET 5 feed
* Add `<NoWarn/>` for XA4301
> Bump to .NET 6.0.100-preview.1.21081.5

- NuGet.config
Context: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610
Context: https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/12676/ncident-help-for-Substitution-attack-risk-from-multiple-package-feeds
There is a Package Substitution Attack inherent in NuGet, whereby
if multiple package sources provide packages with the same name,
it is *indeterminate* which package source will provide the package.
There are two ways to prevent this attack:
1. Use `//packageSources/clear` and have *only one*
`//packageSources/add` entry in `NuGet.config`
2. Use `//packageSources/clear` and *fully trust* every
`//packageSources/add` entry in `NuGet.config`.
`NuGet.org` *cannot* be …
> [nuget.config] use <clear/> and dotnet-public feed

- azure-pipelines.yml
The hosted macOS images should have [all recent Xcode versions][0]
pre-installed, and we can use `xcode-select` to use the version needed
by iOS.
[0]: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode
> [ci] Use pre-installed Xcode 12.3

- README.md
- azure-pipelines.yml
iOS workloads need to be updated to include the version with Windows support.
> Adds instructions for building iOS from Windows

- HelloiOS/AppDelegate.cs
Thanks for sharing these samples and making it so easy to get started with .NET 6 for Xamarin!
I had an issue where it looked like the iOS sample wasn't deploying properly, because my simulator was set to use dark mode, and the sample background color was hard-coded. Currently, if the sample is run on a device in dark mode, the status bar, background, and label are all rendered white.
This PR addresses that by checking for the iOS 13 API, and using system background color if available, otherwise it will default to white. For simplicity the label color is set to just blue. This isn't an ideal pattern, but I wanted to keep the changes minimal while ensuring compatibility and a good first run experience.
I tested with the simulator for iOS 14.4 and iOS 11.4.
I didn't see a CLA or advice for …
> Update iOS sample to be visible in dark mode

- .vscode/tasks.json
The `Build` command was prompting for `Project->Build Target->Configuration`.
However the `Run` command was prompting for
`Project->TargetFramework->AttachDebugger->Configuration`.
It makes more sense to prompt for the debugger last. That way the order
of the prompts are similar.
> Fix the ordering of the VSCode prompts.

- HelloMacCatalyst/AppDelegate.cs
In dark mode, the app was completely white.
It seems we can just use no background color, and I get the system default background color.
I used `Blue` text like the iOS sample.
> [catalyst] make label visible in dark mode

- README.md
- azure-pipelines.yml
Changes: https://github.com/xamarin/xamarin-macios/compare/cc1918e6...98c8649d
This fixes the 'dotnet new' templates.
> Update iOS & Mac Catalyst Builds

- HelloMaui/Directory.Build.targets
To enable the switch between target frameworks on VisualStudio the LaunchProfiles capability need to be enabled.
By default, it is enabled but this capability is removed by our SDKs because the HEAD projects (Android and iOS) does not use this IDE feature to display devices on the start button.
The _KeepLaunchProfiles property avoids that removal in order to have LaunchProfiles enabled on VisualStudio.
The MauiSingleProject project capability is required to identify single projects and when VisualStudio loads a project with this capability the initialization required for Android and iOS is executed, starting the services for both platforms.
The Android and iOS project capabilities cannot be used to do that because only one set of these capabilities (related to the current TargetFramework) …
> Sets the msbuild property _KeepLaunchProfiles to true and adds the MauiSingleProject project capability

- HelloMacOS/Info.plist
- HelloMaui/HelloMaui.csproj
- HelloMaui/iOS/Info.plist
- HelloiOS/HelloiOS.csproj
- HelloiOS/Info.plist
- README.md
- azure-pipelines.yml
- fsharp/HelloiOSFSharp/HelloiOSFSharp.fsproj
- fsharp/HelloiOSFSharp/Info.plist
- global.json
* Android 11.0.200.195
* iOS 14.4.100.1320
* macOS 11.1.100.1373
* MacCatalyst 14.3.100.465
* Bump min iOS versions.
> Bump to .NET 6.0.100-preview.3.21201.23

- HelloAndroid/HelloAndroid.csproj
I updated our AndroidX packages via:
https://github.com/xamarin/AndroidX/pull/247
The current build is based on the .NET 6 Preview 3 bits.
> Bump to AndroidX net6preview03

- Directory.Build.targets
- HelloMaui/Directory.Build.targets
- README.md
- azure-pipelines.yml
- global.json
* Android: 11.0.200.226
* iOS: 14.5.100.620
* macOS: 11.3.100.620
* MacCatalyst: 14.5.100.620
* Install Microsoft OpenJDK 11 Preview
iOS & MacCatalyst:
* Temporarily enable the linker until we get machine pools with Big
Sur and Xcode 12.5
> Bump to .NET 6.0.100-preview.4.21215.1

- README.md
- azure-pipelines.yml
- global.json
* Bump to .NET 6.0.100-preview.4.21255.9
* Remove links to mobile workload installers
* Add instructions for `dotnet workload install` command
> Update README.md for Preview 4

- HelloMauiWinUI3/HelloMauiWinUI3 (Package)/Package.appxmanifest
- azure-pipelines.yml
The Azure DevOps agents now have VS2019 16.10 installed, so the WinUI3 build step can be uncommented. Confirmation can be found here [https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019).
> Enable WinUI 3 builds in Azure DevOps

- NuGet.config
On .NET 6 preview 4 we need to add a source to restore MAUI NuGet packages.
We can do it running CLI commands:
```
dotnet new nugetconfig
dotnet nuget add source -n maui-preview https://aka.ms/maui-preview/index.json
```
Or adding the source on VS:
I do prefer the second way beacause it works on any new MAUI project.
Alas it doesn't work if there is, as in the maui-samples repo, a NuGet.config file with a `<clear />` comand 😢
So I've created this PR adding the needed source  to the file itself.
> Update NuGet.config (add source to restore MAUI NuGet packages).

- HelloAndroid/HelloAndroid.csproj
We want to rely on all dependencies to exist on NuGet.org.
Eventually, we should be able to delete the NuGet.config file in this repo completely.
> [android] use AndroidX stable packages

- Directory.Build.targets
- HelloMaui/App.xaml.cs
- HelloMaui/HelloMaui.csproj
- HelloMauiWinUI3/HelloMauiWinUI3/HelloMauiWinUI3.csproj
- NuGet.config
- README.md
- azure-pipelines.yml
- global.json
* Use `maui-check --main`
* Workaround for `runtimeconfig.json`
* Use `UseMaui=true` instead of `@(PackageReference)`
* Change to `App.xaml.cs`
* Restore `NuGet.config` for nightly packages
> Updates for .NET 6 Preview 6

- azure-pipelines.yml
Context: https://github.com/Redth/dotnet-maui-check/issues/66#issuecomment-880676197
> [build] skip WebView2 check in maui-check

- HelloiOS/Main.cs
```
/Users/poupou/git/microsoft/maui-samples/HelloiOS/Main.cs(12,13): warning CS0618: 'UIApplication.Main(string[]?, string?, string?)' is obsolete: 'Use the overload with 'Type' instead of 'String' parameters for type safety.' [/Users/poupou/git/microsoft/maui-samples/HelloiOS/HelloiOS.csproj]
```
ref: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1355753
note: A larger template update will soon be available.
> [HelloiOS] Fix warning when building with preview 6

- 6.0/Apps/WeatherTwentyOne/src/WeatherTwentyOne/Platforms/MacCatalyst/TrayService.cs
- 6.0/Apps/WeatherTwentyOne/src/WeatherTwentyOne/WeatherTwentyOne.csproj
The status item gets created, but is more or less invisible (though clickable), because the icon doesn't get copied.
Fixes #284
> fix #284 Status Tray not displaying on Mac

- 6.0/UserInterface/Handlers/CreateHandlerDemo/VideoDemos/VideoDemos.csproj
.NET 7 SR1 automatically includes WinAppSDK v1.2. However, this hasn't been backported to .NET 6. This PR ensures that videos can be played on Windows in .NET 6.
`MediaPlayerElement` on Windows requires the use of WinAppSDK v1.2, which in turn requires the use of Microsoft.Windows.SDK.BuildTools v 10.0.22621.1.
> Force use of WinAppSDK 1.2 in .NET 6

- 7.0/Animations/README.md
- 7.0/Apps/PointOfSale/README.md
- 7.0/Apps/WeatherTwentyOne/README.md
- 7.0/Navigation/FlyoutPageSample/README.md
- 7.0/Navigation/ShellFlyoutSample/README.md
- 7.0/Navigation/ShellMixedSample/README.md
- 7.0/Navigation/ShellTabBarSample/README.md
- 7.0/Navigation/TabbedPage/README.md
- Upgrading/CustomRenderer/README.md
- Upgrading/README.md
I don't think there's a need to also tag .NET MAUI samples as .NET Core. Also, we're trying to get rid of the ".NET Core" label since Core has been dropped from the name.
Contributes to https://github.com/dotnet/docs/issues/35970
> Remove dotnet-core metadata

- 7.0/UserInterface/Views/TwoPaneView/TwoPaneViewSample.csproj
The TwoPaneView sample doesn't work due to out of date package references.
This updates the packages references from the RC to the release versions.
This will resolve issue #321
> Update TwoPaneViewSample RC packages references to release versions

- 7.0/Fundamentals/Localization/LocalizationDemo/LocalizationDemo.csproj
- 7.0/Fundamentals/Localization/LocalizationDemo/LocalizedPage.xaml
- 7.0/Fundamentals/Localization/LocalizationDemo/SettingsPage.xaml
Use wildcards in the .csproj to include platform resources. In particular, this removes the need to use the `OnPlatform` markup extension when loading localized images on Windows.
> Update localization sample

- .github/workflows/build-all.yml
- 7.0/Beginners-Series/MauiApp2/MainPage.xaml.cs
This adds a GitHub Action that can be triggered manually.
When triggered, it will loop through this repo searching for all *.csproj files and build them all through `dotnet build` on both Windows and macOS.
It will **not** fail early. It will go through all the projects and if it fails it will just put that on a list. In the summary of a GitHub Action run you will find a list of all the projects that have been built with the status: succeeded or failed.
This will give us an easy tool to quickly (although a full run takes 1-2 hours, optimizations are possible here) check if all samples build successfully.
> Add a GitHub Action to build all the samples in this repo

- 7.0/Fundamentals/Localization/LocalizationDemo/LocalizationDemo.csproj
The Build Action for the resources on the Android project were not correct. This resulted in an error while loading the project in Visual Studio.
Fixes #373
> Correct Build Action for Localization sample

- .github/workflows/build-all.yml
- 8.0/UserInterface/Views/GraphicsViewDemos/GraphicsViewDemos/GraphicsViewDemos.csproj
- 8.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/WorkingWithMaps.csproj
- 8.0/WebServices/TodoREST/TodoAPI/TodoAPI.csproj
- Upgrading/CustomRenderer/MauiCustomRenderer/MauiCustomRenderer.csproj
- eng/excluded_projects_macos.txt
- eng/excluded_projects_windows.txt
This change adds a way to exclude certain projects from the automated build in the GitHub Action.
Add projects with relative paths and use forward slashes in the `./eng/excluded_projects.txt` file, for example: `./8.0/Sample/App/Project.csproj`
The `#` sign can be used for comments, those will be filtered out.
Projects that need to be excluded right now have been added.
See this in action on this fork here: https://github.com/jfversluis/maui-samples/actions/runs/6932207281
> Add the ability to skip certain projects from automated building

- .github/workflows/build-pr.yml
This adds a CI build for PRs that will look for the changed projects and only build those to make sure we don't introduce any breaking changes.
Builds are ran on both Windows and macOS.
> Add GitHub Action to build PRs (only changed projects)

- 8.0/UITesting/BasicAppiumNunitSample/README.md
Correct grammar for "run" - "to be run", "can be run", and so on are correct usages.
> Update README.md grammar fixes for ran vs run

- 8.0/Fundamentals/Shell/Xaminals/Extensions/CollectionViewExtenstions.cs
- 8.0/Fundamentals/Shell/Xaminals/Views/BearsPage.xaml.cs
- 8.0/Fundamentals/Shell/Xaminals/Views/CatsPage.xaml.cs
- 8.0/Fundamentals/Shell/Xaminals/Views/DogsPage.xaml.cs
- 8.0/Fundamentals/Shell/Xaminals/Views/ElephantsPage.xaml.cs
- 8.0/Fundamentals/Shell/Xaminals/Views/MonkeysPage.xaml.cs
A common scenario is that users will select something and then navigate away. Once they navigate back the element is still selected which will result in users being unable to reselect the given item.
https://github.com/dotnet/maui/pull/21490#discussion_r1623301225
The original issue also points to our samples, because our samples don't allow reselection.
https://github.com/dotnet/maui/issues/20273
Fixes https://github.com/dotnet/docs-maui/issues/2362
> [Collection view] Handle a reselect scenario

- 8.0/Navigation/FlyoutPageSample/FlyoutPageSample/AppFlyout.xaml.cs
This change fixes #219, #229 and #311.
The FlyoutPageSample app runs into a crash issue on Windows with the following error message: `System.InvalidOperationException: Can't change IsPresented when setting Default`.
Full StackTrace:
```
System.InvalidOperationException: Can't change IsPresented when setting Default
at Microsoft.Maui.Controls.FlyoutPage.OnIsPresentedPropertyChanging(BindableObject sender, Object oldValue, Object newValue)
at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, …
```
> Fix FlyoutPageSample OnSelectionChanged crash issue 

- 9.0/Apps/DeveloperBalance/DeveloperBalance/Pages/Controls/ChipDataTemplateSelector.cs
- 9.0/Apps/DeveloperBalance/DeveloperBalance/Pages/ProjectDetailPage.xaml
- 9.0/Apps/DeveloperBalance/DeveloperBalance/Pages/ProjectDetailPage.xaml.cs
This is a bit better practice!
Coming through here: https://github.com/dotnet/maui/issues/25515
This change will also end up in the new .NET MAUI project template
> Move DataTemplateSelector to separate file for Developer Balance

- .github/workflows/build-all.yml
- .github/workflows/build-pr.yml
Required to prevent build failures due to the upcoming CDN changes
see dotnet/core#9671
> Update dotnet actions

- 9.0/Apps/DeveloperBalance/Pages/Controls/CategoryChart.xaml
- 9.0/Apps/DeveloperBalance/Pages/MainPage.xaml
This PR changes the Radial Chart to a Doughnut chart. With the Radial chart, there were limited options on how to make the chart's information fully accessible for users who are color-blind and who use a keyboard only.
With the new doughnut chart, the data labels show the category name and the value without needing tooltips or a legend.
The only concern is that with these data labels on the mobile devices is if they are too long, they will not show up.
Adresses:
* https://github.com/dotnet/maui/issues/26232
* https://github.com/dotnet/maui/issues/26234
* https://github.com/dotnet/maui/issues/26236
> Change the radial chart to doughnut chart

- 9.0/Apps/DeveloperBalance/Pages/MainPage.xaml
Make Project Section from MainPage accessible using the keyboard  in the DeveloperBalance App.
Related with https://github.com/dotnet/maui/pull/27224
> Fix keyboard navigation issue on DeveloperBalance App

- 9.0/Apps/DeveloperBalance/Pages/MainPage.xaml
- 9.0/Apps/DeveloperBalance/Pages/ProjectListPage.xaml
As mentioned in this PR: https://github.com/dotnet/maui/pull/27322
These appears to be a [bug](https://github.com/dotnet/maui/issues/27325) with CollectionView2 when trying to use these changes in our template. For the time being, we should keep the BindableLayout and make the BindableLayout more accessible for keyboard users.
This PR reverts https://github.com/dotnet/maui-samples/pull/573  and  https://github.com/dotnet/maui-samples/pull/572
> Revert Keyboard DeveloperAccessibility PRs

- 8.0/UserInterface/Views/SwitchDemos/SwitchDemos/Views/SwitchVisualStatesPage.xaml
- 9.0/UserInterface/Views/SwitchDemos/SwitchDemos/Views/SwitchVisualStatesPage.xaml
As discussed [here](https://github.com/dotnet/docs-maui/pull/2765).  It's ideal to use `VisualStateGroupList` whenever we are defining our own Visual states. Since default MAUI template comes with defined style for Switch.
> Adding VisualStateGroupList for Switch Visual State examples

- 9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/Resources/Raw/wwwroot/scripts/HybridWebView.js
In .NET (MAUI) 9 SR4 it's necessary to serialise all return values. Previously, strings were a special case.
> HybridWebView: serialize all return values

- 9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/MainPage.xaml.cs
- 9.0/UserInterface/Views/HybridWebViewDemo/HybridWebViewDemo/Resources/Raw/wwwroot/index.html
.NET (MAUI) 9 SR4 adds support for asynchronous methods in the `HybridWebView` control, which these sample updates demo.
> HybridWebView: async support

- 9.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos/Views/HeadersAndFooters/VerticalListHeaderFooterDataTemplatePage.xaml
`{Binding .}` is unrequited here.
> Remove unnecessary binding

- .github/workflows/quest-bulk.yml
This runs monthly on all open issues. That moves any slipped issues that aren't being added to a new sprint into the backlog sprint.
> Add a monthly cron job

- .github/workflows/build-all.yml
- .github/workflows/build-pr.yml
closes: internal
This pull request updates the GitHub Actions workflows to support multiple .NET SDK versions and improves the build process by introducing a new variable to track skipped projects. Below are the key changes grouped by theme:
* [`.github/workflows/build-all.yml`](diffhunk://#diff-7682a9fd2942d8a81f55c30abd512b277b1b1eb7c5f16b2c4d88323de90e55d0L19-R26): Updated the `.NET SDK` installation step to support versions `8.0.x`, `9.0.x`, and `10.0.x`, including prerelease versions. The step name was also updated to reflect this change.
* [`.github/workflows/build-pr.yml`](diffhunk://#diff-15b4de36ac797b24d56f24c4403e979f20eabd06c3d49f3ffdceb0ebec3c0fb2L23-R30): Made the same updates as in `build-all.yml` to support multiple .NET SDK versions and include prerelease versions.
* …
> Fix GH Actions build

- 10.0/Apps/DeveloperBalance/PageModels/ProjectDetailPageModel.cs
- 10.0/Apps/DeveloperBalance/Pages/ProjectDetailPage.xaml
- 9.0/Apps/DeveloperBalance/PageModels/ProjectDetailPageModel.cs
Selected tags are not restored on MainPage after returning from ProjectDetailPage.
After the changes introduced in [PR-611](https://github.com/dotnet/maui-samples/pull/611), when a tag was initially selected, navigating to ProjectDetailPage caused it to be deleted in the [ToggleTag](https://github.com/dotnet/maui-samples/blob/main/9.0/Apps/DeveloperBalance/PageModels/ProjectDetailPageModel.cs#L256) method through the [SelectionChanged](https://github.com/dotnet/maui-samples/blob/main/9.0/Apps/DeveloperBalance/PageModels/ProjectDetailPageModel.cs#L298)  logic. This incorrect logic resulted in the selected tags being lost on the MainPage.
Updated SelectionChanged command logic that compares the current selection with the previous one, updates the IsSelected property for newly selected or …
> Fix Selected Tags Not Restored on MainPage After Navigation
